### ISSUE TITLE
server not loading error 

### ISSUE THREAD

**Issue by ToBinio** [repeated-pleasant-games/tabletop-old#56]
so you came into the join screen and when you wrote a name and pressed join there was like a 50% chance that it loaded and if it didnt you just had a gray / white screnn so without the grid and with out the settings 
error:
![error](https://user-images.githubusercontent.com/81473300/127360419-f31e9c8b-bbc6-4cd5-84df-35f3020ec13a.PNG)
![even more error](https://user-images.githubusercontent.com/81473300/127362920-693b03a7-68bf-49ba-9469-45e4e7b805cb.PNG)

**Comment by ToBinio** [comment]
![error the next](https://user-images.githubusercontent.com/81473300/127363885-b313670d-2eff-40e5-af4c-52c58b01e8e9.PNG)

**Comment by joebobmiles** [comment]
:postal_horn: Huzzah! :postal_horn:

This issue is resolved in 1.0.0-alpha.11!
