### ISSUE TITLE
moving Actors...

### ISSUE THREAD

**Issue by ToBinio** [repeated-pleasant-games/tabletop-old#67]
You cant move an Actor if another one is directly under him (not on him under...) like 
▢▢▢
▢■▢
▢■▢
▢▢▢

becouse if you try to click the upper one you just mark the (name / text) of the lower one

**Comment by joebobmiles** [comment]
:postal_horn: Huzzah! :postal_horn:

This issue is resolved in 1.0.0-alpha.21!
