### ISSUE TITLE
Camera zoom

### ISSUE THREAD

**Issue by ToBinio** [repeated-pleasant-games/tabletop-old#68]
if you zoom out to much ( until  the screens turns black).

and then zoom in again the witdh of the boarder changes but the perspectiv of the camera doesnt.

error:
![image](https://user-images.githubusercontent.com/81473300/129764905-826ee9fe-4a6b-4aed-a83f-0723cd388aef.png)

**Comment by joebobmiles** [comment]
:postal_horn: Huzzah! :postal_horn:

This issue is resolved in 1.0.0-alpha.19!
