### ISSUE TITLE
zooming sets your Camera to 0,0

### ISSUE THREAD

**Issue by ToBinio** [repeated-pleasant-games/tabletop-old#71]
If you Zoom to far out (the max point) your camera position is still "remathed" so if you zoom out it sets 0,0 where ever your mouce position is.

I think it comes couse you "remathed" automaticly if you scroll but still "remathed" it if you are on max zoom distance

**Comment by joebobmiles** [comment]
:postal_horn: Huzzah! :postal_horn:

This issue is resolved in 1.0.0-alpha.22!
